system:
  mode: 1
  distribute: False
  amp_level: 'O0'
  seed: 1024
  log_interval: 20
  val_while_train: False
  val_start_epoch: 0
  drop_overflow_update: True

common:
  character_dict_path: &character_dict_path pgnet/utils/dict/ic15_dict.txt

model:
  type: e2e
  transform: null
  backbone:
    name: pgnet_backbone
    pretrained: False
  neck:
    name: E2eFpn
  head:
    name: PGNetHead
  pretrained: ./pretrain/pgnet/best_param.ckpt
  resume: False

loss:
  name: PGLoss
  tcl_bs: 64
  max_text_length: 50
  max_text_nums: 30
  pad_num: 36
loss_scaler:
  type: dynamic
  loss_scale: 512
  scale_factor: 2
  scale_window: 1000

postprocess:
  name: PGPostProcess
  score_thresh: 0.5
  point_gather_mode: align
  character_dict_path: *character_dict_path
  valid_set: totaltext

scheduler:
  scheduler: cosine_decay
  lr: 0.001
  num_epochs: 600
  warmup_epochs: 50
  decay_epochs: 550

optimizer:
  opt: adam
  beta1: 0.9
  beta2: 0.999
  weight_decay: 0.0001

metric:
  name: E2EMetric
  mode: B
  gt_mat_dir: ./train_data/total_text/test/gt
  character_dict_path: *character_dict_path
  main_indicator: f_score_e2e

train:
  gradient_accumulation_steps: 2
  clip_grad: True 
  clip_norm: 5.0
  ema: True
  ckpt_save_dir: './tmp_det'
  dataset_sink_mode: True
  pred_cast_fp32: False
  dataset:
    type: PGDataset
    dataset_root: ./train_data
    data_dir: total_text/train
    label_file: total_text/train/train.txt
    dataset: 'totaltext'
    sample_ratio: [1.0]
    transform_pipeline:
      - DecodeImage:
          img_mode: BGR
          to_float32: False
      - E2ELabelEncodeTrain:
      - PGProcessTrain:
          batch_size: 14
          use_resize: True
          use_random_crop: False
          min_crop_size: 24
          min_text_size: 4
          max_text_size: 512
          point_gather_mode: align
          max_text_length: 50
          max_text_nums: 30
          tcl_len: 64
          character_dict_path: *character_dict_path
    output_columns: ['images',  'tcl_maps', 'tcl_label_maps', 'border_maps','direction_maps', 'training_masks', 'label_list', 'pos_list', 'pos_mask']
    net_input_column_index: [0]
    label_column_index: [1, 2, 3, 4, 5, 6, 7, 8]

  loader:
    shuffle: True
    batch_size: 14
    drop_remainder: True
    num_workers: 16

eval:
  ckpt_load_path: './tmp_det/best.ckpt'
  dataset_sink_mode: True
  dataset:
    type: PGDataset
    dataset_root: ./train_data
    data_dir: total_text/test
    label_file: total_text/test/test.txt
    dataset: totaltext
    sample_ratio: 1.0
    transform_pipeline:
      - DecodeImage:
          img_mode: BGR
          to_float32: False
      - E2ELabelEncodeTest:
          keep_invalid: True
          lower: True
          max_text_len: 50
          character_dict_path: *character_dict_path
      - E2EResizeForTest:
          max_side_len: 768
          dataset: totaltext
      - NormalizeImage:
          bgr_to_rgb: False
          is_hwc: True
          mean: imagenet
          std: imagenet
      - ToCHWImage:
    output_columns: ['image', 'shape_list', 'polys', 'texts', 'ignore_tags', 'img_id']
    net_input_column_index: [0]
    label_column_index: [2, 3, 4, 5]

  loader:
    shuffle: False
    batch_size: 1
    drop_remainder: False
    num_workers: 2
