batch_size: 64
lr: 0.001
lr_backbone_s: 0.002
model_root: ./models
n_epoch: 100
n_pretrain_epochs: 50
source_dataset_name: MNIST
source_image_root: ./dataset/MNIST
target_dataset_name: mnist_m
target_image_root: ./dataset/mnist_m
weight_decay: 1.0e-05
device_target: Ascend
backbone_ckpt_file: ./models/backbone_t.ckpt
classifier_ckpt_file: ./models/class_classifier.ckpt
imageSize: 28
linearSize: 800
file_name: "DANN.air"
file_format: "AIR"


